from typing import Any

import numpy as np

def simulate(replay: Any) -> "State": ...

class DeathEvent:
    timestep: int
    player: int

class CaptureEvent:
    timestep: int
    captor: int
    captured: int

class NeutralizeEvent:
    timestep: int
    player: int

class State:
    @property
    def timestep(self) -> int: ...
    @property
    def alive_count(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    @property
    def alive(self) -> list[bool]: ...
    @property
    def has_kill(self) -> list[bool]: ...
    @property
    def generals(self) -> list[int]: ...
    @property
    def cities(self) -> list[int]: ...
    @property
    def death_events(self) -> list[DeathEvent]: ...
    @property
    def capture_events(self) -> list[CaptureEvent]: ...
    @property
    def neutralize_events(self) -> list[NeutralizeEvent]: ...

    @property
    def ownership(self) -> np.ndarray: ...
    @property
    def armies(self) -> np.ndarray: ...
    @property
    def cities_mask(self) -> np.ndarray: ...
    @property
    def damage_off_all(self) -> np.ndarray: ...

    @property
    def snapshots_ownership(self) -> list[np.ndarray]: ...
    @property
    def snapshots_armies(self) -> list[np.ndarray]: ...
    @property
    def snapshots_cities_mask(self) -> list[np.ndarray]: ...
    @property
    def snapshots_len(self) -> int: ...
