from typing import Any

import numpy as np

def ping() -> None: ...
def simulate(
    replay: Any, perspective_player_ids: list[int] | tuple[int, ...] = (),
) -> "State": ...

class DeathEvent:
    timestep: int
    player: int

class CaptureEvent:
    timestep: int
    captor: int
    captured: int

class NeutralizeEvent:
    timestep: int
    player: int

class State:
    @classmethod
    def from_python(cls, py_state: Any) -> "State": ...

    # Scalars / lists
    @property
    def timestep(self) -> int: ...
    @property
    def alive_count(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    @property
    def moves_cursor(self) -> int: ...
    @property
    def afks_cursor(self) -> int: ...
    @property
    def updates_since_move(self) -> int: ...
    @property
    def alive(self) -> list[bool]: ...
    @property
    def has_kill(self) -> list[bool]: ...
    @property
    def generals(self) -> list[int]: ...
    @property
    def cities(self) -> list[int]: ...
    @property
    def death_events(self) -> list[DeathEvent]: ...
    @property
    def capture_events(self) -> list[CaptureEvent]: ...
    @property
    def neutralize_events(self) -> list[NeutralizeEvent]: ...

    # Numpy
    @property
    def ownership(self) -> np.ndarray: ...
    @property
    def armies(self) -> np.ndarray: ...
    @property
    def cities_mask(self) -> np.ndarray: ...
    @property
    def actions_source(self) -> np.ndarray: ...
    @property
    def actions_dest(self) -> np.ndarray: ...
    @property
    def actions_is50(self) -> np.ndarray: ...
    @property
    def damage_sym_all(self) -> np.ndarray: ...
    @property
    def damage_sym_pre(self) -> np.ndarray: ...
    @property
    def damage_off_all(self) -> np.ndarray: ...
    @property
    def damage_off_pre(self) -> np.ndarray: ...
    @property
    def input_buffer_lengths(self) -> list[int]: ...
    @property
    def input_buffer_contents(self) -> list[list[int]]: ...
    @property
    def snapshots_ownership(self) -> list[np.ndarray]: ...
    @property
    def snapshots_armies(self) -> list[np.ndarray]: ...
    @property
    def snapshots_cities_mask(self) -> list[np.ndarray]: ...
    @property
    def snapshots_len(self) -> int: ...

    # Step body methods
    def apply_production(self) -> None: ...
    def buffer_pending_moves(self, m_timestep: np.ndarray, m_index: np.ndarray) -> None: ...
    def select_candidates(
        self, m_index: np.ndarray, m_source: np.ndarray, m_dest: np.ndarray
    ) -> list[int]: ...
    def is_valid(
        self, move_idx: int, m_index: np.ndarray, m_source: np.ndarray, m_dest: np.ndarray
    ) -> bool: ...
    def record_action(
        self,
        move_idx: int,
        m_index: np.ndarray,
        m_source: np.ndarray,
        m_dest: np.ndarray,
        m_is50: np.ndarray,
    ) -> None: ...
    def attack(
        self,
        move_idx: int,
        m_index: np.ndarray,
        m_source: np.ndarray,
        m_dest: np.ndarray,
        m_is50: np.ndarray,
    ) -> None: ...
    def execute_attack(
        self,
        move_idx: int,
        m_index: np.ndarray,
        m_source: np.ndarray,
        m_dest: np.ndarray,
        m_is50: np.ndarray,
    ) -> None: ...
    def execute_player_capture(self, captured: int, captor: int) -> None: ...
    def try_neutralize_player(self, p: int) -> None: ...
    def kill_player(self, p: int) -> None: ...
    def kill_all_but_strongest(self) -> None: ...
    def priority_sort(
        self,
        candidates: list[int],
        m_index: np.ndarray,
        m_source: np.ndarray,
        m_dest: np.ndarray,
    ) -> list[int]: ...
    def dependency_loop(
        self, sorted_candidates: list[int], m_source: np.ndarray, m_dest: np.ndarray,
    ) -> list[int]: ...
    def process_pending_afks(self, a_timestep: np.ndarray, a_index: np.ndarray) -> None: ...
    def snapshot(self) -> None: ...
    def step(
        self,
        m_timestep: np.ndarray,
        m_index: np.ndarray,
        m_source: np.ndarray,
        m_dest: np.ndarray,
        m_is50: np.ndarray,
        a_timestep: np.ndarray,
        a_index: np.ndarray,
    ) -> bool: ...
