"""
POC Modal entrypoint — Modal-blessed install path with full dep pinning.

Run with:
    uv run modal run cloud-poc/modal_entry.py

Image construction:
  1) debian_slim base with Python 3.14.
  2) `uv_pip_install` from a fully-pinned requirements file (generated by
     `tools/regen_modal_reqs.sh` from the workspace uv.lock).
  3) `uv_pip_install` our local cloud-train-poc package — by this point
     torch is already present, so this layer just installs the package.

Layer ordering optimizes cache reuse: deps (slow, rarely change) before
package source (fast, changes often).
"""

from pathlib import Path

import modal

REPO_ROOT = Path(__file__).resolve().parent.parent
CLOUD_POC = REPO_ROOT / "cloud-poc"

image = (
    modal.Image.debian_slim(python_version="3.14")
    # `requirements=` takes a local filesystem path; Modal reads + ships it.
    .uv_pip_install(requirements=[str(CLOUD_POC / "modal_requirements.txt")])
    .add_local_file(
        CLOUD_POC / "pyproject.toml",
        "/pkg/pyproject.toml",
        copy=True,
    )
    .add_local_dir(
        CLOUD_POC / "cloud_train_poc",
        "/pkg/cloud_train_poc",
        copy=True,
        ignore=["__pycache__", "*.pyc"],
    )
    .uv_pip_install("/pkg")
)

app = modal.App("cloud-train-poc", image=image)


@app.function()
def remote_hello() -> dict:
    from cloud_train_poc.work import hello

    return hello()


@app.local_entrypoint()
def main():
    result = remote_hello.remote()
    print("got back from cloud:")
    for k, v in result.items():
        print(f"  {k}: {v}")
