"""Assemble the model-architecture markdown: diagram embeds + generated config
and parameter tables. The whole doc is an artifact — like the SVGs, it is
regenerated from the live config, not hand-edited.

Torch enters only in `_param_table` (it instantiates the model to count
parameters); the import is deferred so diagram-only runs stay torch-free.
"""

from __future__ import annotations

from training.bc.model_config import ModelConfig
from utils.format import format_count, format_pct, md_table


# Diagram file names (in the doc's sibling diagrams/ dir), embedded in order.
OVERVIEW_SVG = "diagrams/model-overview.svg"
TRUNK_SVG = "diagrams/trunk-pyramid-u.svg"
TRUNK_COMPACT_SVG = "diagrams/trunk-pyramid-u-compact.svg"


def _config_table(cfg: ModelConfig) -> str:
    rows = [
        ("obs channels (`in_ch`)", str(cfg.in_ch)),
        ("board (H × W)", f"{cfg.H} × {cfg.W}"),
        ("trunk widths (outer / middle / inner)",
         f"{cfg.outer_width} / {cfg.middle_width} / {cfg.inner_width}"),
        ("trunk depths (N / M / M)",
         f"{cfg.n_outer} / {cfg.m_middle} / {cfg.m_inner}"),
        ("value head variant", cfg.value_head_variant),
        # Train-time regularization (eval no-op, no params) — listed so the
        # config table fully reflects the value-head settings a run was swept on.
        ("value head dropout — 2d / flat / skip-2d (train-time)",
         f"{cfg.value_head_dropout2d} / {cfg.value_head_dropout} "
         f"/ {cfg.value_head_skip_dropout2d}"),
    ]
    return md_table(["field", "value"], rows)


def _param_table(cfg: ModelConfig) -> str:
    from training.bc.model.bc_model import BCModel

    model = BCModel(cfg)
    total = sum(p.numel() for p in model.parameters())
    rows = [(name, sum(p.numel() for p in child.parameters()))
            for name, child in model.named_children()]
    rows.sort(key=lambda r: r[1], reverse=True)
    table: list[list[object]] = [
        [f"`{name}`", format_count(count), format_pct(count / total)]
        for name, count in rows
    ]
    table.append(["**total**", f"**{format_count(total)}**", "**100%**"])
    return md_table(["component", "params", "share"], table,
                    align=["left", "right", "right"])


def build_doc(cfg: ModelConfig) -> str:
    return f"""# Model architecture — `bc.model`

<!-- Generated by tools/gen_model_arch_doc.py from MODEL_CONFIG_DEFAULTS. Do not edit by hand. -->

## Overview

![Model overview]({OVERVIEW_SVG})

## Trunk — Pyramid Module (2-contraction U-Net)

![Trunk pyramid U]({TRUNK_SVG})

Compact view — per-level ResBlock runs collapsed:

![Trunk pyramid U, compact]({TRUNK_COMPACT_SVG})

## Config

{_config_table(cfg)}

## Parameters

{_param_table(cfg)}
"""
